name: CI

on: [push, pull_request]

jobs:
  CI:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: ./ci.sh
        env:
          CODECOV_TOKEN: 734e735c-3495-4b5d-b11b-022e520fdc2b
