name: "Worker job"
on:
  repository_dispatch:
    types: [worker-job]

env:
  pyver: 3.7

jobs:
  sandboxed:
    runs-on: ubuntu-latest
    name: "sandboxed-${{ github.event.client_payload.jobid }}"

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.worker_revision }}
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.pyver }}
      # This should make worker jobs way faster! Unfortunately it
      # doesn't work:
      #
      #   https://github.com/actions/cache/issues/63
      #
      # - id: cache-workenv
      #   uses: actions/cache@v1
      #   with:
      #     path: workenv
      #     key: "workenv-${{ runner.os }}-${{ env.pyver }}-${{ hashFiles('requirements.txt') }}"
      - run: python -m venv workenv && workenv/bin/pip install -r requirements.txt
      - run: workenv/bin/python -m snekomatic.worker_entrypoint sandboxed
      - uses: actions/upload-artifact@v1
        with:
          name: worker-artifacts-dir
          path: worker-artifacts-dir/

  privileged:
    runs-on: ubuntu-latest
    name: "privileged-${{ github.event.client_payload.jobid }}"
    needs: sandboxed

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.worker_revision }}
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ env.pyver }}
      # This has to go after actions/checkout, because if we put it
      # first then actions/checkout will delete the downloaded
      # artifacts.
      - uses: actions/download-artifact@v1
        with:
           name: worker-artifacts-dir
      - run: python -m venv workenv && workenv/bin/pip install -r requirements.txt
      - run: workenv/bin/python -m snekomatic.worker_entrypoint privileged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
