name: "Worker job"
on:
  repository_dispatch:
    types: [worker-job]

jobs:
  unprivileged:
    runs-on: ubuntu-latest
    name: "unprivileged-${{ github.event.client_payload.jobid }}"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - run: pip install -r requirements.txt
      - run: python -m snekomatic.worker unprivileged
      - uses: actions/upload-artifact@v1
        with:
          name: worker-artifacts-dir
          path: worker-artifacts-dir/

  privileged:
    runs-on: ubuntu-latest
    name: "privileged-${{ github.event.client_payload.jobid }}"
    needs: unprivileged

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - uses: actions/download-artifact@v1
        with:
           name: worker-artifacts-dir
      - run: pip install -r requirements.txt
      - run: python -m snekomatic.worker privileged
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
